[project]
name = "fastxai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
authors = [{name="chenjunfeng", email="cjf_junfeng@163.com"}]

classifiers = [
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: FastAPI",
]

dependencies = [
    "aioredis>=2.0.1",
    "asyncpg>=0.31.0",
    "fastapi-structlog>=0.7.0",
    "fastapi-users>=15.0.1",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.123.5",
    "fastmcp>=2.13.2",
    "hypercorn>=0.18.0",
    "orjson>=3.11.4",
    "passlib[bcrypt]>=1.7.4",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.12.0",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy[asyncio]>=2.0.44",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
#index-url = "https://mirrors.aliyun.com/pypi/simple"
